#!/bin/bash

GIT_DIR="/home/ksomnia/ksomnia/.git"
TARGET="/opt/ksomnia"
BRANCH="main"

while read oldrev newrev ref
do
  if [[ $ref = refs/heads/$BRANCH ]];
  then
    echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
    git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f
  else
    echo "Ref $ref received. Doing nothing."
  fi
done
